spring:
  application:
    name: holerite
  datasource:
    url: jdbc:mysql://localhost:3306/folha_de_pagamento?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: seu_user_do_My_SQL
    password: senha_de_acesso_do_MySQL
  jpa:
    hibernate:
      ddl-auto: update
